# Generated by Django 3.1.1 on 2020-09-27 00:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('is_main', models.BooleanField(default=False)),
                ('photo', models.CharField(blank=True, default='https://upload.wikimedia.org/wikipedia/commons/7/7c/User_font_awesome.svg', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='task_creator.employee')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='task_creator.employee')),
            ],
        ),
        migrations.CreateModel(
            name='DailyTaskConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('starting_time', models.DateTimeField(blank=True, null=True)),
                ('ending_time', models.DateTimeField(blank=True, null=True)),
                ('total_time', models.IntegerField(default=0)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_creator.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_creator.task')),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_creator.dailytasklist')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('task_connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_creator.dailytaskconnector')),
            ],
        ),
    ]
