# Generated by Django 3.1.1 on 2020-09-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bitrix_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
