# Generated by Django 3.1.1 on 2020-09-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_creator', '0002_task_bitrix_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bitrix_id',
            field=models.IntegerField(unique=True),
        ),
    ]
