# Generated by Django 3.1.1 on 2020-09-12 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_creator', '0003_auto_20200910_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytaskconnector',
            name='employee_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='task_creator.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_creator.task')),
            ],
        ),
    ]
