# Generated by Django 3.1.1 on 2020-09-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_creator', '0004_auto_20200912_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
