# Generated by Django 3.1.1 on 2020-10-13 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_creator', '0004_auto_20201013_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
