# Generated by Django 3.1.1 on 2020-09-13 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_creator', '0006_auto_20200912_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='task_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task_creator.dailytasklist'),
            preserve_default=False,
        ),
    ]
