# Generated by Django 3.1.1 on 2020-10-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_creator', '0006_auto_20201013_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authmodel',
            name='bitrix_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
