# Generated by Django 3.1.1 on 2020-09-13 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_creator', '0007_comment_task_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='task_list',
        ),
        migrations.AddField(
            model_name='comment',
            name='task_connector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task_creator.dailytaskconnector'),
            preserve_default=False,
        ),
    ]
