# Generated by Django 3.1.1 on 2020-09-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_creator', '0009_dailytaskconnector_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytaskconnector',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
