# Generated by Django 3.1.1 on 2020-09-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_creator', '0010_dailytaskconnector_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/7/7c/User_font_awesome.svg', max_length=300),
        ),
    ]
