# Generated by Django 3.1.1 on 2020-09-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_creator', '0012_auto_20200922_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytaskconnector',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailytaskconnector',
            name='ending_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytaskconnector',
            name='starting_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytaskconnector',
            name='total_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
