# Generated by Django 3.1.1 on 2020-09-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_creator', '0013_auto_20200926_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytaskconnector',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
    ]
